apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 10s

  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: postgres:5432
    database: sensor_monitor
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      timezone: UTC
