{
 "title": "Main dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество сенсоров онлайн",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensors_online_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество сенсоров оффлайн",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensors_offline_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process CPU usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"sensor-monitor:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время с последних данных от DHT22",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_monitor",
     "rawSql": "SELECT\n  EXTRACT(EPOCH FROM (NOW() - last_seen_at)) AS \"Секунд с последних данных от DHT22\"\nFROM\n  sensor\nwhere \n  type = 'DHT22'"
    }
   ]
  },
  {
   "title": "Время с последних данных от BMP280",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_monitor",
     "rawSql": "SELECT\n  EXTRACT(EPOCH FROM (NOW() - last_seen_at)) AS \"Секунд с последних данных от BMP280\"\nFROM\n  sensor\nwhere \n  type = 'BMP280'"
    }
   ]
  },
  {
   "title": "Уровень газа MQ-2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_monitor",
     "rawSql": " SELECT timestamp AS \"time\",\n         raw_value AS \"Кол-во газа\"\n  FROM mq2_reading                                                                                                                     \n  WHERE $__timeFilter(timestamp)\n  ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Расстояние HC-SR04",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_monitor",
     "rawSql": "SELECT timestamp AS \"time\",\n         distance_cm AS \"Расстояние см\"\n  FROM hcsr04_reading                  \n  WHERE $__timeFilter(timestamp)\n  ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Время с последних данных от MQ-2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_monitor",
     "rawSql": "SELECT\n  EXTRACT(EPOCH FROM (NOW() - last_seen_at)) AS \"Секунд с последних данных от MQ-2\"\nFROM\n  sensor\nwhere \n  type = 'MQ2'"
    }
   ]
  },
  {
   "title": "Время с последних данных от HC-SR04",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_monitor",
     "rawSql": "SELECT\n  EXTRACT(EPOCH FROM (NOW() - last_seen_at)) AS \"Секунд с последних данных от HC-SR04\"\nFROM\n  sensor\nwhere \n  type = 'HCSR04'"
    }
   ]
  },
  { "title": "New panel", "type": "alertlist", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 12 } },
  {
   "title": "Влажность DHT22",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_monitor",
     "rawSql": "SELECT timestamp AS \"time\",                                                                                                          \n         humidity AS \"Влажность %\"\n  FROM dht22_reading\n  WHERE $__timeFilter(timestamp)                                                                                                       \n  ORDER BY timestamp "
    }
   ]
  },
  {
   "title": "Давление BMP280",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_monitor",
     "rawSql": "SELECT timestamp AS \"time\",\n         pressure_hpa AS \"Давление hPa\"\n  FROM bmp280_reading\n  WHERE $__timeFilter(timestamp)                                                                                                       \n  ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Температура DHT22 и BMP280",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensor_monitor",
     "rawSql": "SELECT timestamp AS \"time\",                                                                                                          \n         temperature AS \"Температура DHT22\"                                                                                                        \nFROM dht22_reading           \nWHERE $__timeFilter(timestamp)\nORDER BY timestamp;"
    },
    {
     "dataset": "sensor_monitor",
     "rawSql": "SELECT timestamp AS \"time\",                                                                                                          \n       temperature AS \"Температура BMP280\"\nFROM bmp280_reading                                                                                                                  \nWHERE $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Утечка газа",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "dataset": "sensor_monitor",
     "rawSql": "SELECT timestamp AS \"time\",\n         CASE WHEN gas_detected THEN 1 ELSE 0 END AS \"Тревога\"\n  FROM mq2_reading\n  WHERE $__timeFilter(timestamp)\n  ORDER BY timestamp"
    }
   ]
  }
 ]
}